name: amd64
on:
  workflow_dispatch:
jobs:
  build:
    name: amd64
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: apk add build-base pkgconf autoconf automake libtool git perl openssl-libs-static openssl-dev linux-headers
        shell: ash {0}
      - run: git clone https://github.com/esnet/iperf.git ~/iperf3 && cd ~/iperf3
      - run: cd ~/iperf3
      - run: ./configure --disable-shared --enable-static-bin --prefix=$HOME
      - run: make
      - run: make install
      - run: echo 'iperf_release_name='$(strings ~/bin/iperf3 | grep -E '^iperf 3\.[0-9]{1,3}$') >> $GITHUB_ENV
      - run: echo 'iperf_tag='$(strings ~/bin/iperf3 | grep -E '^iperf 3\.[0-9]{1,3}$' | awk '{print $2}') >> $GITHUB_ENV
      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "${{ env.GITHUB_WORKSPACE }}/bin/iperf3"
          replacesArtifacts: true
          tag: "${{ env.iperf_tag }}"
          name: "${{ env.iperf_release_name }}"
          bodyFile: " ${{ env.GITHUB_WORKSPACE }}/bin/iperf3"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
