name: iperf3 qemu multiarch
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [iperf3]
        os_id: [alpine]
        os_version_id: [edge]
        arch: [i386, amd64, arm32v6, arm32v7, arm64v8, ppc64le, s390x]
        include:
          - arch: i386
            docker_arch: linux/i386
          - arch: amd64
            docker_arch: linux/amd64
          - arch: arm32v6
            docker_arch: linux/arm/v6
          - arch: arm32v7
            docker_arch: linux/arm/v7
          - arch: arm64v8
            docker_arch: linux/arm64
          - arch: ppc64le
            docker_arch: linux/ppc64le
          - arch: s390x
            docker_arch: linux/s390x

    name: ${{ matrix.name }} ${{ matrix.os_id }}:${{ matrix.os_version_id }} ${{ matrix.arch }}

    env:
      CDN: http://dl-cdn.alpinelinux.org/alpine/edge/main/

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker multiarch bootstrap
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Create docker multiarch ${{ matrix.docker_arch }} container
        run: docker run --name multiarch -it -d -w /root --platform ${{ matrix.docker_arch }} -v ${{ github.workspace }}:/root ${{ matrix.arch }}/${{ matrix.os_id }}:${{ matrix.os_version_id }}

      - name: Run apk update
        run: docker exec multiarch apk update --repository=${{ env.CDN }}

      - name: Run apk upgrade
        run: docker exec multiarch apk upgrade --repository=${{ env.CDN }}

      - name: apt-get install the core build dependencies
        run: docker exec multiarch apk add build-base pkgconf autoconf automake curl libtool git tar curl perl openssl-dev openssl-libs-static linux-headers

      - name: clone esnet/iperf
        run: docker exec multiarch git clone https://github.com/esnet/iperf.git /root/iperf3

      - name: Configure
        run: docker exec multiarch bash -c 'cd /root/iperf3 && ./configure --host=${{ matrix.CHOST }} --disable-shared --with-openssl --enable-static-bin --prefix=/root'

      - name: Build
        run: docker exec multiarch bash -c 'cd /root/iperf3 && make && make install'

      - name: Rename iperf3 to ${{ matrix.arch }}
        run: mv -f ${{ github.workspace }}/bin/iperf3 ${{ github.workspace }}/bin/${{ matrix.arch }}

      - name: Create path to binary env
        run: echo 'iperf_path='$(echo ${{ github.workspace }}/bin/${{ matrix.arch }}) >> $GITHUB_ENV

      - name: Create release name env
        run: echo 'iperf_release_name='$(strings ${{ env.iperf_path }} | grep -E '^iperf 3\.[0-9]{1,3}$') >> $GITHUB_ENV

      - name: Create tag env
        run: echo 'iperf_tag='$(strings ${{ env.iperf_path }} | grep -E '^iperf 3\.[0-9]{1,3}$' | awk '{print $2}') >> $GITHUB_ENV

      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          artifacts: "${{ env.iperf_path }}"
          replacesArtifacts: true
          tag: "${{ env.iperf_tag }}"
          name: "${{ env.iperf_release_name }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
